[package]
name = "fedimintd-floresta"
description = "fedimintd with florestad as the Bitcoin backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fedimint-floresta = { path = "../fedimint-floresta" }
fedimintd = { workspace = true }
